name: deploy

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          presist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: Setup Expo
        uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true
      
      - name: Install dependencies
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./frontend_new
          build: npm run build:testing
          start: npm run start:integration-test-server
          record: true
        env:
          CI: true
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }} 
