name: Build and Deploy
on: 
  push:
    branches:
      - main
jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Cypress Test
      uses: cypress-io/github-action@v4
      with:
        working-directory: ./frontend
        command: npx cypress run
        browser: chrome
